# Shell and editors
brew "bash"
brew "fd"
brew "gh"
brew "git-lfs"
brew "gnu-sed"
brew "lazygit"
brew "neovide"
brew "neovim"
brew "ripgrep"
brew "stylua"
brew "tree"

# Language runtimes and build tools
brew "bazel"
brew "buf"
brew "cmake"
brew "gcc"
brew "go"
brew "go-task"
brew "maven"
brew "mockery"
brew "node"
brew "openjdk"
brew "pipx"
brew "pkgconf"
brew "tree-sitter"
brew "utf8proc"
brew "uv"

# Cloud, containers and infrastructure
brew "act"
brew "argocd"
brew "awscli"
brew "fluxcd/tap/flux"
brew "helm"
brew "istioctl"
brew "kubernetes-cli"
brew "terragrunt"
brew "trivy"
brew "veracode/tap/veracode-cli"

# Utilities, documentation and formatting
brew "beeftornado/rmtree/brew-rmtree"
brew "cloc"
brew "cookiecutter"
brew "ffmpeg"
brew "grpcui"
brew "hf"
brew "mdbook"
brew "prettier"
brew "vale"

# Applications and fonts
cask "copilot-cli"
cask "db-browser-for-sqlite"
cask "font-noto-color-emoji"
cask "iterm2"
cask "ngrok"
cask "orbstack"
