#!/usr/bin/env bash

set -euo pipefail

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
git -C dotbot submodule sync --quiet --recursive
git submodule update --init --recursive dotbot

exec dotbot/bin/dotbot -d "$PWD" -c install.conf.yaml "$@"
