-- Basic
require("options")
require("keymaps")
require("plugins")
require("colorscheme")
require("autocmds")
-- Plugins
require("plug.nvim-tree")
require("plug.bufferline")
require("plug.lualine")
require("plug.telescope")
require("plug.project")
require("plug.startup")
require("plug.nvim-treesitter")
require("plug.indent_blankline")
require("plug.toggleterm")
require("plug.comment")
require("plug.gitsigns")
require("plug.nvim-autopairs")
require("plug.nvim-surround")
require("plug.illuminate")
require("plug.impatient")
-- LSP
require("lsp")
-- require("lsp.cmp")
-- require("lsp.ui")
-- DAP
-- require("dap.init")
