require('indent_blankline').setup({
  show_first_indent_level = false,
  filetype_exclude = {
    "help",
    "startify",
    "aerial",
    "alpha",
    "dashboard",
    "packer",
    "neogitstatus",
    "NvimTree",
    "ToggleTerm",
    "Trouble",
  },
  char = '│',
  use_treesitter_scope = false,
  show_trailing_blankline_indent = false,
  show_current_context = true,
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  buftype_exclude = { 'terminal', 'nofile' },
})

